- name: Generate networkd bat device (dom0)
  template:
    src: network0.j2
    dest: "/etc/systemd/network/10-bat0.network"

- name: Create mesh_fastd daemon config directories (dom0)
  file: path=/etc/fastd/mesh_fastd state=directory

- name: Generate fastd config (dom0)
  template:
    src: fastd.conf.j2
    dest: "/etc/fastd/mesh_fastd/fastd.conf"

- name: Check if mesh_fastd remotes file exists (dom0)
  stat: path=/etc/fastd/mesh_fastd/remotes.conf
  register: remotes

- name: Ensure mesh_fastd remotes file exits (dom0)
  when: not remotes.stat.exists
  file: path=/etc/fastd/mesh_fastd/remotes.conf state=touch
  notify: Restart mesh_fastd

- name: Generate secret.conf link (dom0)
  file:
    src: "/etc/fastd/secret.conf"
    dest: "/etc/fastd/mesh_fastd/secret.conf"
    state: link

- name: Generate backbone.conf link (dom0)
  notify: Restart mesh_fastd
  file:
    src: "/etc/fastd/backbone.conf"
    dest: "/etc/fastd/mesh_fastd/backbone.conf"
    state: link

- name: Start mesh_fastd on boot (dom0)
  service: name=fastd@mesh_fastd enabled=yes state=started
