---

- hosts: monitor

  vars_prompt:
    - name: "hostname"
      prompt: "which hostname?"
      private: no

  tasks:
    - name: start maintainance
      command: "zabbix-cli -C 'remove_host_from_hostgroup \"{{hostname}}\" \"Maintenance with data\"'"
