---

- name: Copy icinga2 config files
  copy:
    src: "{{ item }}"
    dest: "/etc/icinga2/conf.d/"
    owner: "root"
    mode: 0644
  with_fileglob:
    - "files/*"
  notify: Reload icinga2

- name: Generate hosts.conf
  notify: Reload icinga2
  template:
    src: "hosts.conf.j2"
    dest: "/etc/icinga2/conf.d/hosts.conf"
