---
fqdn: "awx.ffh.zone"

nginx_sites:
- domain: "awx.ffh.zone"
  root: "/var/www/awx.ffh.zone"
  tls: "true"
  tls_redirect_to_https: "true"
  locations:
    - location: "/"
      type: "proxy"
      proxy_forward_url: "http://localhost:8000/"
      allow_connection_upgrade: "true"
