---

servername: monitor
fqdn: "monitor.ffh.zone"

networkd_configures:
- iface: eth0
  dhcp: true
  addresses:
    - 2a01:4f8:221:100c::1003/64
  gateway6: 2a01:4f8:221:100c::2

zabbix_server_dbname: "zabbix"
zabbix_server_dbhost: "localhost"
zabbix_server_dbport: "3306"
zabbix_server_dbuser: "zabbix"
zabbix_server_dbpassword: "{{ log_zabbix_dbpassword }}"
zabbix_server_db_login_user: "root"
zabbix_server_db_login_password: ""
zabbix_server_create_dbname: "true"
zabbix_server_create_dbuser: "true"
zabbix_server_host: "localhost"

zabbix_agent_server: "127.0.0.1"
zabbix_agent_server_active: "127.0.0.1"

mysql_root_password: "{{ log_mysql_root_password }}"
mysql_databases:
- name: "{{ zabbix_server_dbname }}"
mysql_users:
- name: "{{ zabbix_server_dbuser }}"
  host: "{{ zabbix_server_dbhost }}"
  password: "{{ zabbix_server_dbpassword }}"
  priv: "{{ zabbix_server_dbname }}.*:ALL"

netbox_stable: true
netbox_stable_version: 2.8.9
netbox_socket: "0.0.0.0:8011"
netbox_superuser_password: "netbox"
netbox_config:
  ALLOWED_HOSTS:
    - "*"
  MEDIA_ROOT: "{{ netbox_shared_path }}/media"
  REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
  SCRIPTS_ROOT: "{{ netbox_shared_path }}/scripts"
netbox_database_socket: "{{ postgresql_unix_socket_directories[0] }}"
netbox_webhooks_enabled: true

postgresql_users:
  - name: "{{ netbox_database_user }}"
    role_attr_flags: CREATEDB,NOSUPERUSER

redis_bind: 127.0.0.1

nginx_sites:
- domain: netbox.ffh.zone
  root: /var/www/netbox.ffh.zone
  tls: true
  tls_redirect_to_https: true
  locations:
    - location: /
      type: proxy
      proxy_forward_url: http://localhost:8011/
- domain: zabbix.ffh.zone
  root: /var/www/zabbix.ffh.zone
  tls: true
  tls_redirect_to_https: true
  php: true
  custom_config: |
          location / {
            alias /usr/share/zabbix;
            disable_symlinks on;
            fastcgi_param PHP_VALUE "
              max_execution_time 300
              memory_limit 128M
              post_max_size 16M
              upload_max_filesize 2M
              max_input_time 300
              max_input_vars 10000
              always_populate_raw_post_data -1
            ";
          }

