---

- hosts: awx

  roles:
    - { name: ffh.ferm, tags: ferm }
    - { name: ffh.admin, tags: admin }
    - { name: ffh.cli_tools, tags: cli_tools }
    - { name: ffh.zabbix-agent, tags: zabbix-agent }
    - { name: ffh.cron-apt, tags: cron-apt }
    - { name: ffh.awx, tags: awx }
    - { name: ffh.nginx, tags: nginx }

  vars:
    nginx_sites:
    - domain: awx.ffh.zone
      root: /var/www/awx.ffh.zone
      tls: true
      tls_redirect_to_https: true
      locations:
        - location: /
          type: proxy
          proxy_forward_url: http://localhost:8000/
          allow_connection_upgrade: true
