---

- hosts: awx
  pre_tasks:
    - name: "Import pre_tasks: reboot-required.yml"
      import_tasks: "include/reboot-required.yml"
      tags: [always]
  roles:
    - { name: ffh.ferm, tags: ferm }
    - { name: ffh.admin, tags: admin }
    - { name: ffh.cli_tools, tags: cli_tools }
    - { name: ffh.zabbix-agent, tags: zabbix-agent }
    - { name: ffh.cron-apt, tags: cron-apt }
    - { name: ffh.awx, tags: awx }
    - { name: ffh.nginx, tags: nginx }
