---

- hosts: leintor
  roles:
    - { name: ffh.ferm, tags: ferm }
    - { name: ffh.exitnode, tags: exitnode }
    - { name: ffh.cli_tools, tags: cli_tools }
    - { name: ffh.networkd, tags: networkd }
    - { name: ffh.simple_mail, tags: simple_mail }
    - { name: ffh.journald, tags: journald }
    - { name: ffh.admin, tags: admin }
    - { name: ffh.cron-apt, tags: cron-apt }
    - { name: ffh.babeld, tags: babeld }
    - { name: ffh.zabbix-agent, tags: zabbix-agent }
    - { name: ffh.apinger, tags: apinger }
    - { name: ffh.routingnode, tags: routingnode }
    - { name: ffh.telegraf, tags: telegraf }
    # Backups
    - { name: ffh.restic, tags: restic }
