---

- hosts: monitor
  roles:
    - { name: ffh.networkd, tags: networkd }
    - { name: ffh.ferm, tags: ferm }
    # admin stuff
    - { name: ffh.simple_mail, tags: simple_mail }
    - { name: ffh.journald, tags: journald }
    - { name: ffh.admin, tags: admin }
    - { name: ffh.cli_tools, tags: cli_tools }
    - { name: ffh.cron-apt, tags: cron-apt }
    # special
    - { name: DavidWittman.redis, tags: redis }
    - { name: geerlingguy.postgresql, tags: postgresql }
    - { name: lae.netbox, tags: netbox }
    - { name: ffh.zabbix-server, tags: zabbix-server }
    - { name: ffh.zabbix-frontend, tags: zabbix-frontend }
    - { role: ffh.nginx, tags: nginx }
    # Backups
    - { name: ffh.restic, tags: restic }
