---

- hosts: web
  roles:
    - { name: ffh.networkd, tags: networkd }
    - { name: ffh.ferm, tags: ferm }
    # admin stuff
    - { name: ffh.simple_mail, tags: simple_mail }
    - { name: ffh.journald, tags: journald }
    - { name: ffh.admin, tags: admin }
    - { name: ffh.cli_tools, tags: cli_tools }
    - { name: ffh.cron-apt, tags: cron-apt }
    # special
    - { role: ffh.nginx, tags: nginx }
    - { role: ffh.fnorden.net, tags: fnorden.net }
    - { role: ffh.foswiki, tags: foswiki }
    - { role: ffh.git2cal, tags: git2cal }
    # - { role: ffh.taskserver, tags: taskserver }
    - { name: ffh.zabbix-agent, tags: zabbix-agent }
    - { name: ffh.burginfo, tags: burginfo }
    # Backups
    - { name: ffh.restic, tags: restic }
